name: 이미지 compress
on:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: 'zhZsh5BB7WGh18461DJMrKZsBMDzBmvf'
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit_message: '이미지 최적화 by TinyPNG'
