name: 이미지 compress
on:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches:
    - main
    paths:
    - '**.png'
    - '**.jpg'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # checkout v3 사용
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Compress images using TinyPNG
        run: |
          IFS=$'\n'
          find "$(pwd)" -type f \( -iname '*.png' -o -iname '*.jpg' \) | while read -r img; do
            compressed_url=$(curl --user api:$TINY_PNG_KEY --data-binary @"$img" https://api.tinify.com/shrink | jq -r '.output.url')
            curl -o "$img" --location "$compressed_url"
          done
        env:
          TINY_PNG_KEY: ${{ secrets.TINY_PNG_KEY }}
