name: Optimize Images with TinyPNG

on:
  push:
    branches:
      - main
    paths:
      - '**.png'
      - '**.jpg'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compress images with TinyPNG
        uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.zhZsh5BB7WGh18461DJMrKZsBMDzBmvf }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: '이미지 최적화 by TinyPNG'
